<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ExerciseImage extends BaseExerciseImage
{
    public function postDelete($event)
    {
        $path = sfConfig::get('sf_upload_dir').'/';
        if(is_file($path.$this->filename))
            @unlink($path.$this->filename);
    }
}