<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Exercise extends BaseExercise
{
    public function canBeEdited($user)
    {
        if( $this->owner_id == $user->getId() ) // owner
            return true;

        if($this->is_shareable)
        {
            if( $user->isSuperAdmin() )
                return true;

            if( ( ( $user->hasGroup('coaches') || $user->hasGroup('moderator') ) && $this->owner_id != $user->getId() )  || $this->owner_id == $user->getId() )
                return true;
        }

        return false;
    }

    public function isOwner($user)
    {
        return ( $this->owner_id == $user->getId() ); // owner
    }
}