autoload:
  swift_mailer_classes:
    name: SWIFT Mailer classes
    path: %SF_PLUGINS_DIR%/sfSwiftPlugin/lib/swift/lib
    recursive:      on
  plugins_module_lib:
    name:           plugins module lib
    path:           '%SF_PLUGINS_DIR%/*/modules/*/lib'
    prefix: 3
    recursive:      on
  gsImageProcess:
    name:           blah blah
    path:           '%SF_PLUGINS_DIR%/gsImageProcessorPlugin/lib'
    recursive:      on