<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseExerciseSet extends sfDoctrineRecord
{
  public function setTableDefinition()
  {
    $this->setTableName('exercise_set');
    $this->hasColumn('id', 'integer', 4, array('type' => 'integer', 'unsigned' => true, 'primary' => true, 'autoincrement' => true, 'length' => '4'));
    $this->hasColumn('otype', 'integer', 1, array('type' => 'integer', 'unsigned' => true, 'length' => '1'));
    $this->hasColumn('s1', 'string', 32, array('type' => 'string', 'length' => '32'));
    $this->hasColumn('i1', 'integer', 4, array('type' => 'integer', 'unsigned' => true, 'length' => '4'));

    $this->setSubClasses(array('RepSet' => array('otype' => '1'), 'TimeSet' => array('otype' => '1')));
  }

  public function setUp()
  {
    $this->hasMany('ProgramExercise', array('local' => 'id',
                                            'foreign' => 'exercise_set_id'));
  }
}