<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseExerciseImage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('exercise_images');
        $this->hasColumn('id', 'integer', 4, array('type' => 'integer', 'unsigned' => true, 'primary' => true, 'autoincrement' => true, 'length' => '4'));
        $this->hasColumn('exercise_id', 'integer', 4, array('type' => 'integer', 'unsigned' => true, 'length' => '4'));
        $this->hasColumn('filename', 'string', 128, array('type' => 'string', 'length' => '128'));
        $this->hasColumn('width', 'integer', 3, array('type' => 'integer', 'unsigned' => true, 'length' => '3'));
        $this->hasColumn('height', 'integer', 3, array('type' => 'integer', 'unsigned' => true, 'length' => '3'));
        $this->hasColumn('caption', 'string', 128, array('type' => 'string', 'length' => '128'));
    }

    public function setUp()
    {
        $this->hasOne('Exercise', array('local' => 'exercise_id',
                                        'foreign' => 'id',
                                        'onDelete' => 'CASCADE'));

        $i18n0 = new Doctrine_Template_I18n(array('fields' => array(0 => 'caption')));
        $this->actAs($i18n0);
    }
}