<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseExerciseImage extends Image
{
    public function setUp()
    {
        parent::setUp();
    $this->hasOne('Exercise', array('local' => 'owner_id',
                                        'foreign' => 'id'));
    }
}