<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseExerciseTag extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('exercise_tag');
        $this->hasColumn('id', 'integer', 4, array('type' => 'integer', 'unsigned' => true, 'primary' => true, 'autoincrement' => true, 'length' => '4'));
        $this->hasColumn('tag_id', 'integer', 4, array('type' => 'integer', 'unsigned' => true, 'length' => '4'));
        $this->hasColumn('exercise_id', 'integer', 4, array('type' => 'integer', 'unsigned' => true, 'length' => '4'));
    }

    public function setUp()
    {
        $this->hasOne('Exercise', array('local' => 'exercise_id',
                                        'foreign' => 'id',
                                        'onDelete' => 'CASCADE'));

        $this->hasOne('Tag', array('local' => 'tag_id',
                                   'foreign' => 'id',
                                   'onDelete' => 'CASCADE'));
    }
}