<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseMuscle extends sfDoctrineRecord
{
  public function setTableDefinition()
  {
    $this->setTableName('muscles');
    $this->hasColumn('id', 'integer', 4, array('type' => 'integer', 'unsigned' => true, 'primary' => true, 'autoincrement' => true, 'length' => '4'));
    $this->hasColumn('name', 'string', 255, array('type' => 'string', 'length' => '255'));
    $this->hasColumn('insertio', 'string', 255, array('type' => 'string', 'length' => '255'));
    $this->hasColumn('origio', 'string', 255, array('type' => 'string', 'length' => '255'));
  }

  public function setUp()
  {
    $this->hasMany('Exercise', array('refClass' => 'ExerciseMuscle',
                                     'local' => 'muscle_id',
                                     'foreign' => 'exercise_id'));
  }
}