rendering: ~
security:
  class: sfGuardBasicSecurityFilter

# insert your own filters here
security:
  class: sfGuardRememberMeFilter

url:
  class: gsUrlFilter

cache:     ~
common:    ~
execution: ~
